In [8]:
import pickle
import pandas as pd

pickle_file = 'sbert/sbert_data.pickle'
df = pd.read_pickle(pickle_file)

In [9]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   model                     3 non-null      object
 1   num_clusters              3 non-null      object
 2   clustering_time           3 non-null      object
 3   run_datetime              3 non-null      object
 4   inertia                   3 non-null      float64
 5   silhouette_avg            3 non-null      float32
 6   silhouette_avg            3 non-null      float32
 7   db_index                  3 non-null      float64
 8   ch_index                  3 non-null      float32
 9   silhouette_avg_clusters   3 non-null      object
 10  max_iterations            3 non-null      object
 11  description_time          3 non-null      object
 12  cluster_description_dict  3 non-null      object
 13  comment_cluster_list      3 non-null      object
dtypes: float32(3), float64(2), object(9)
memory usage: 428.0+ bytes
None
              model num_clusters clustering_time    run_datetime     inertia  \
0  all-MiniLM-L6-v2           10               3  24.10.29_22.43  264.130844
1  all-MiniLM-L6-v2           25               2  24.10.29_22.43  230.632674
2  all-MiniLM-L6-v2           50               3  24.10.29_22.45  200.321315

   silhouette_avg  silhouette_avg  db_index   ch_index  \
0        0.122199        0.122199  3.015791  22.381540
1        0.096332        0.096332  2.888140  12.192515
2        0.096635        0.096635  2.294403   7.903216

                             silhouette_avg_clusters max_iterations  \
0  {0: 0.22707508504390717, 1: 0.1283800899982452...         100000
1  {0: 0.0209979135543108, 1: -0.0227648485451936...         100000
2  {0: 0.11362066864967346, 1: 0.0490758307278156...         100000

  description_time                           cluster_description_dict  \
0                3  {0: ['flexibility', 'opportunities', 'culture'...
1               27  {0: ['work', 'managers', 'from', 'supportive',...
2               80  {0: ['were', 'from', 'manager', 'support', 'co...

                                comment_cluster_list
0  [8, 9, 8, 9, 4, 9, 9, 8, 3, 9, 2, 9, 1, 4, 0, ...
1  [11, 16, 11, 23, 21, 17, 17, 1, 23, 23, 24, 23...
2  [45, 42, 12, 37, 8, 26, 17, 28, 22, 17, 33, 37...

In [10]:
display(df.head())

,model,num_clusters,clustering_time,run_datetime,inertia,silhouette_avg,silhouette_avg,db_index,ch_index,silhouette_avg_clusters,max_iterations,description_time,cluster_description_dict,comment_cluster_list
0,all-MiniLM-L6-v2,10,3,24.10.29_22.43,264.130844,0.122199,0.122199,3.015791,22.381540,"{0: 0.22707508504390717, 1: 0.1283800899982452...",100000,3,"{0: ['flexibility', 'opportunities', 'culture'...","[8, 9, 8, 9, 4, 9, 9, 8, 3, 9, 2, 9, 1, 4, 0, ..."
1,all-MiniLM-L6-v2,25,2,24.10.29_22.43,230.632674,0.096332,0.096332,2.888140,12.192515,"{0: 0.0209979135543108, 1: -0.0227648485451936...",100000,27,"{0: ['work', 'managers', 'from', 'supportive',...","[11, 16, 11, 23, 21, 17, 17, 1, 23, 23, 24, 23..."
2,all-MiniLM-L6-v2,50,3,24.10.29_22.45,200.321315,0.096635,0.096635,2.294403,7.903216,"{0: 0.11362066864967346, 1: 0.0490758307278156...",100000,80,"{0: ['were', 'from', 'manager', 'support', 'co...","[45, 42, 12, 37, 8, 26, 17, 28, 22, 17, 33, 37..."